Partly fixes #4124
argoproj/argo pull request #4128
Opened 2020-09-24 15:54 UTC by secretlifeof

Checklist:

* [b] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [c] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [no] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-09-28 18:44 UTC, alexec commented on examples/README.md
> +    - name: A
please can you revert these whitespace changes?

2020-09-28 18:44 UTC, alexec requested changes
Please revert whitespace changes.

2020-11-19 17:41 UTC, alexec commented
Bump! Close or continue?

2020-11-19 18:01 UTC, secretlifeof commented
Sorry. For being so extremely late. I have copied the formatting from the raw markdown file. What do you think about creating a **.vsc** folder with format settings so that this will not happen?

2020-11-19 18:03 UTC, alexec approved these changes
I don't feel strongly about white-space.

2020-11-19 18:05 UTC, secretlifeof commented
Next time it will not happen

2020-11-19 18:20 UTC, merged