fix(cli): add validate args in delete command
argoproj/argo pull request #4142
Opened 2020-09-28 13:43 UTC by gosoon

run `argo delete` command without arguments and no output, want output helpfunc. 
```
# argo delete
# echo $?
0
```
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-09-28 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4142) before we can accept your contribution.<br/><hr/>**feilei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4142) it.</sub>

2020-09-28 13:59 UTC, simster7 approved these changes
Thanks!

2020-09-28 14:28 UTC, simster7 requested changes
Seems like an e2e test is failing because we allow deletion by flags: e.g. `argo delete --all`, or `argo delete --completed`. These flags are not considered part of the `args`, so when executing commands like these `len(args) == 0` is true.

Can you add some checks to make sure that if `len(args) == 0` that also none of the relevant flags are being used before printing help and returning 1?

2020-09-29 04:42 UTC, gosoon commented
/retest

2020-09-29 04:45 UTC, gosoon commented
> Seems like an e2e test is failing because we allow deletion by flags: e.g. `argo delete --all`, or `argo delete --completed`. These flags are not considered part of the `args`, so when executing commands like these `len(args) == 0` is true.
> 
> Can you add some checks to make sure that if `len(args) == 0` that also none of the relevant flags are being used before printing help and returning 1?

ok.

2020-09-29 14:17 UTC, simster7 commented
Re-running the CI

2020-09-29 14:30 UTC, simster7 approved these changes

2020-09-29 15:12 UTC, merged