fix(executor): Retrieve containerId from cri-containerd /proc/{pid}/cgroup. Fixes #4302
argoproj/argo pull request #4309
Opened 2020-10-17 02:22 UTC by cy-zheng

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

2020-10-17 02:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4309) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4309) before we can accept your contribution.<br/><hr/>**chenyu.zheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4309) it.</sub>

2020-10-17 02:29 UTC, cy-zheng commented
#4302

2020-10-17 15:01 UTC, alexec commented on workflow/executor/pns/pns.go
> +					strList := strings.Split(containerID, ":")
Test?

2020-10-17 21:57 UTC, alexec requested changes
please add a test

2020-10-18 01:56 UTC, cy-zheng commented
Can you tell me where the corresponding test file is? I am willing to write some unit/e2e tests, but I can’t find the original test code. @alexec

2020-10-18 02:28 UTC, cy-zheng commented
> please add a test

The original e2e tests show that the code can work well with docker. Do I need to add e2e test based on cri-containerd runtime? Or do I only need to verify correctness at the unit test level? @alexec

2020-10-18 03:50 UTC, cy-zheng commented on workflow/executor/pns/pns.go
> +					strList := strings.Split(containerID, ":")
Unit test has been added.

2020-10-18 23:33 UTC, alexec approved these changes

2020-10-18 23:33 UTC, merged

2020-10-18 23:33 UTC, alexec commented
Lgtm