feat(cli): add selector and field-selector option to terminate
argoproj/argo pull request #4448
Opened 2020-11-03 14:20 UTC by hanjunlee

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

2020-11-03 14:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4448) before we can accept your contribution.<br/>**26** out of **29** committers have signed the CLA.<br/><br/>:white_check_mark: mrtns<br/>:white_check_mark: jcmuller<br/>:white_check_mark: sarabala1979<br/>:white_check_mark: hanjunlee<br/>:white_check_mark: alexec<br/>:white_check_mark: omerfsen<br/>:white_check_mark: posquit0<br/>:white_check_mark: tumido<br/>:white_check_mark: Naisisor<br/>:white_check_mark: mac9416<br/>:white_check_mark: duluong<br/>:white_check_mark: istepura<br/>:white_check_mark: idsvandermolen<br/>:white_check_mark: tomgoren<br/>:white_check_mark: cy-zheng<br/>:white_check_mark: dcherman<br/>:white_check_mark: basanthjenuhb<br/>:white_check_mark: terrytangyuan<br/>:white_check_mark: simster7<br/>:white_check_mark: mruoss<br/>:white_check_mark: LotharKAtt<br/>:white_check_mark: jemisonf<br/>:white_check_mark: process0<br/>:white_check_mark: conanoc<br/>:white_check_mark: AntoineDao<br/>:white_check_mark: aayushrangwala<br/>:x: snyk-bot<br/>:x: jakupovic<br/>:x: dllehr81<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4448) it.</sub>

2020-11-04 20:34 UTC, alexec commented on cmd/argo/commands/terminate.go
> +			if len(args) != 0 && t.isList() {
xargs friendly?

2020-11-04 20:34 UTC, alexec commented on cmd/argo/commands/terminate.go
> +	command.Flags().BoolVar(&t.dryRun, "dry-run", false, "Do not delete the workflow, only print what would happen")
`Do not terminate`?

2020-11-04 20:34 UTC, alexec commented on cmd/argo/commands/terminate.go
> +				if t.dryRun {
dry-run test?

2020-11-05 19:45 UTC, alexec requested changes
Changes requested

2020-11-07 19:55 UTC, alexec approved these changes

2020-11-07 19:55 UTC, alexec commented on test/e2e/cli_test.go
> +	s.testNeedsOffloading()
I don't think this needs offloading?

2020-11-08 04:23 UTC, hanjunlee commented on test/e2e/cli_test.go
> +	s.testNeedsOffloading()
It was already fixed ~

2020-11-09 20:02 UTC, merged