Update configure-artifact-repository.md
argoproj/argo pull request #4462
Opened 2020-11-05 09:47 UTC by igarciar

change configuration of minion section

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-11-05 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4462) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4462) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4462) it.</sub>

2020-11-05 13:27 UTC, simster7 commented on docs/configure-artifact-repository.md
> +brew install helm # mac, helm 3.x
Hmm, we use the `$ ...` convention across our docs (even in other places in this same file). In my opinion, what we currently have is easier to parse and understand.

Do you have a good reason to remove the `$ ...` convention?

2020-11-05 17:19 UTC, alexec requested changes
Thank you. We do need you to sign your commits and make the PR title semantic please.

2020-11-06 11:02 UTC, igarciar commented
Hi,
The problem is when you copy the lines or when you used the link.

in other hand, if you need remark same code is recommended to identify the
type of code. Y mark de code like this:

----------

```*bash*

 brew install helm # mac, helm 3.x
 helm repo add stable
https://kubernetes-charts.storage.googleapis.com/ # official Helm
stable charts
 helm repo update
 helm install argo-artifacts stable/minio --set
service.type=LoadBalancer --set fullnameOverride=argo-artifacts

````

----------

Ignacio García Ruiz
ignacio.garcia.ruiz@gmail.com



El jue., 5 nov. 2020 a las 14:27, Simon Behar (<notifications@github.com>)
escribió:

> *@simster7* commented on this pull request.
> ------------------------------
>
> In docs/configure-artifact-repository.md
> <https://github.com/argoproj/argo/pull/4462#discussion_r518048567>:
>
> > @@ -18,11 +18,11 @@ Subsequent sections will show how to use it.
>
>  ## Configuring Minio
>
> -```
> -$ brew install helm # mac, helm 3.x
> -$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/ # official Helm stable charts
> -$ helm repo update
> -$ helm install argo-artifacts stable/minio --set service.type=LoadBalancer --set fullnameOverride=argo-artifacts
> +```bash
> +brew install helm # mac, helm 3.x
>
> Hmm, we use the $ ... convention across our docs (even in other places in
> this same file). In my opinion, what we currently have is easier to parse
> and understand.
>
> Do you have a good reason to remove the $ ... convention?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/argoproj/argo/pull/4462#pullrequestreview-524256495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE4WD4JOJTD6UAJME5GVZBLSOKR3JANCNFSM4TLEGHDA>
> .
>

2020-12-01 00:32 UTC, alexec commented
Closing. Another PR addressed this.

2020-12-01 00:32 UTC, closed without merging