feat: adds millisecond-level timestamps to argo and workflow-controller
argoproj/argo pull request #4518
Opened 2020-11-11 20:53 UTC by mikhailian

Adding millisecond-level timestamps in follow-up to #2795 so that we have them everywhere and not just in argoexec. Thanks to @astein-te for implementing the original feature request.

2020-11-11 20:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo?pullRequest=4518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo?pullRequest=4518) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo?pullRequest=4518) it.</sub>

2020-11-12 12:53 UTC, simster7 requested changes
I'm wondering if we want to make this setting configurable, but I don't really see a point to doing so. Any thoughts?

2020-11-12 12:53 UTC, simster7 commented on cmd/workflow-controller/main.go
> +	fmt.Println("hello world")
Remove this?

2020-11-12 12:58 UTC, mikhailian commented on cmd/workflow-controller/main.go
> +	fmt.Println("hello world")
Thanks!

2020-11-13 15:48 UTC, simster7 approved these changes
Thank you!

2020-11-13 15:49 UTC, merged