refactor: Use polling model for workflow phase metric
argoproj/argo pull request #4557
Opened 2020-11-18 20:27 UTC by simster7

Fixes: https://github.com/argoproj/argo/issues/4551

Signed-off-by: Simon Behar <simbeh7@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-11-18 20:28 UTC, simster7 commented on workflow/controller/controller.go
> -
Some pork-barrel style changes in this PR

2020-11-18 20:28 UTC, simster7 commented on workflow/controller/controller.go
> +	go wait.Until(wfc.syncWorkflowPhaseMetrics, 5*time.Second, ctx.Done())
I think 5 seconds is a good balance here

2020-11-23 23:16 UTC, alexec requested changes
Without @jessesuen to discus, can we set the polling interval to 1m. I'd rather have lower system load than up-to-date values. I will approve that.

2020-11-24 16:33 UTC, simster7 commented
> Without @jessesuen to discus, can we set the polling interval to 1m. I'd rather have lower system load than up-to-date values. I will approve that.

I'm okay waiting for @jessesuen to discuss. In my opinion 1m is too high, esp. since the load is minimal since we read from the informer

2020-11-24 17:17 UTC, alexec commented
> since the load is minimal since we read from the informer 

Good point. 

This is a blocking issue for v2.12, so I suggest set it to 15s as a compromise and these discus with @jesse next week.

2020-11-24 17:17 UTC, alexec approved these changes

2020-11-24 19:22 UTC, simster7 commented on workflow/controller/indexes/labels.go
> +func MetaLabelIndexFunc(label string) cache.IndexFunc {
Done

2020-11-24 20:02 UTC, merged

2020-12-03 00:55 UTC, alexec commented
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4