feat(executor): Auto create s3 bucket if not present.
argoproj/argo pull request #4574
Opened 2020-11-20 14:15 UTC by alexcapras

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-11-20 18:56 UTC, alexec commented
Assigned to @jessesuen to approve proto changes.

2020-11-20 18:57 UTC, alexec commented
@alexcapras can you please link to the issue and previous PR?

2020-11-20 19:06 UTC, alexcapras commented
> @alexcapras can you please link to the issue and previous PR?

Issue: https://github.com/argoproj/argo/issues/3586
Previous PR: https://github.com/argoproj/argo/pull/4098/files

2020-12-01 19:34 UTC, jessesuen approved these changes
re-approving the proto changes.

2020-12-01 20:51 UTC, alexec commented on pkg/apis/workflow/v1alpha1/workflow_types.go
> +	Region string `json:"region,omitempty" protobuf:"varint,2,opt,name=region"`
why do we need region - isn't still already specified by S3Bucket?

2020-12-01 20:54 UTC, alexec commented on pkg/apis/workflow/v1alpha1/workflow_types.go
> +	Enabled bool `json:"enabled,omitempty" protobuf:"varint,1,opt,name=enabled"`
Do we need `Enabled`? could the existence of `CreateS2BucketOptions` imply enabled?

2020-12-01 20:54 UTC, alexec commented on test/e2e/testdata/output-artifact-with-s3-bucket-creation-disabled.yaml
> +              bucket: bucket-that-does-not-exist-1
looks good to me

2020-12-01 20:54 UTC, alexec commented on test/e2e/testdata/output-artifact-with-s3-bucket-creation-disabled.yaml
> +  entrypoint: output-artifact-with-s3-bucket-creation-disabled
minor - just change entrypoint to `main`

2020-12-01 20:54 UTC, alexec commented on test/e2e/testdata/output-artifact-with-s3-bucket-creation-disabled.yaml
> +        image: argoproj/argosay:v1
can you please use `argosay:v2` - is it much less resource intensive

2020-12-01 20:54 UTC, alexec commented on test/e2e/testdata/output-artifact-with-s3-bucket-creation-enabled.yaml
> +  entrypoint: output-artifact-with-s3-bucket-creation-enabled
as above - rename to `main`

2020-12-01 20:54 UTC, alexec commented on workflow/artifacts/s3/s3.go
> +				bucketExists, err := s3cli.BucketExists(outputArtifact.S3.Bucket)
I suggest we just do a single `MakeBucket` and ignore duplicate errors. 50% of the network requests to go missing

2020-12-02 17:59 UTC, alexec requested changes
Changes requested.

2020-12-02 20:56 UTC, alexec commented
Good work! You have some failing jobs that need remedy and you also need to sync with master and we are ready to merge!

2020-12-02 22:57 UTC, alexec approved these changes

2020-12-02 22:57 UTC, alexec commented on test/e2e/testdata/output-artifact-with-s3-bucket-creation-disabled.yaml
> +# This example demonstrates bucket-creation disabled for s3 output artifacts, when the target bucket does not exist.
delete this file?

2020-12-03 00:10 UTC, alexec commented
TestOutputArtifactS3BucketCreationEnabled failed?

2020-12-03 00:22 UTC, alexcapras commented
> TestOutputArtifactS3BucketCreationEnabled failed?

@alexec Addressed this in my latest commit. Only drawback here is that if the user has enabled `createBucketIfNotPresent` and the `MakeBucket` call fails for a reason (other than the bucket already exists, e.g. insufficient perms), we will try to create it again in the ExponentialBackoff loop. (Because the bucketCreation will fail but we will still try to Put the artifact).

If this is not an issue then i think it should be ok now

2020-12-03 17:01 UTC, merged

2020-12-03 17:02 UTC, alexec commented
Merged. This is currently targeted for v3.0. That'll be some time away, maybe Jan. I'll look into backporting it to v2.12