fix(controller): Prevent tasks with names starting with digit to use either 'depends' or 'dependencies'
argoproj/argo pull request #4598
Opened 2020-11-25 15:55 UTC by terrytangyuan

Fixes https://github.com/argoproj/argo/issues/4570. It looks like `dependencies` is first converted into `depends` to support backwards compatibility ([related code](https://github.com/argoproj/argo/blob/4531d7936c25174b3251e926288866c69fc2dba3/workflow/common/ancestry.go#L100-L127)) so either 'depends' or 'dependencies' should fail the validation. 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-11-25 15:56 UTC, terrytangyuan commented
cc @peng09 @simster7

2020-11-30 16:26 UTC, simster7 requested changes

2020-11-30 16:26 UTC, simster7 commented on workflow/validate/validate.go
> +		if (usingDepends || len(task.Dependencies) > 0) && '0' <= task.Name[0] && task.Name[0] <= '9' {
```suggestion
		if '0' <= task.Name[0] && task.Name[0] <= '9' {
```

Wouldn't this be better?

2020-11-30 18:12 UTC, terrytangyuan commented
@simster7 Thanks. Updated and rebased.

2020-11-30 18:14 UTC, simster7 approved these changes
Thanks, @terrytangyuan

2020-11-30 19:16 UTC, merged