feat(executor): More informative log when executors do not support output param from base image layer
argoproj/argo pull request #4620
Opened 2020-12-01 20:15 UTC by terrytangyuan

Currently if we use k8sapi or kubelet executor with output parameters from base image layer, e.g. `/tmp`, we will see the following warning: 

```
Warning  WorkflowNodeError      9s    workflow-controller  Error node couler-test-2[1].heads-114: failed to save outputs: open /mainctrfs/tmp/dummy.txt: no such file or directory
```

This is a bit misleading and not informative to users.
 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2020-12-02 18:21 UTC, alexec approved these changes

2020-12-02 19:09 UTC, alexec requested changes
Please run `make lint` to fix Golang lint problems.

2020-12-02 19:42 UTC, terrytangyuan commented
@alexec Thanks. Fixed and rebased.

2020-12-02 20:30 UTC, alexec approved these changes

2020-12-02 20:30 UTC, merged

2020-12-03 00:56 UTC, alexec commented
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4