feat(server): add ServiceAccount info to api/v1/userinfo and ui user tab
argoproj/argo pull request #4944
Opened 2021-01-25 13:20 UTC by tczhao

Resolves: #4936

Signed-off-by: Tianchu Zhao <evantczhao@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2021-01-25 15:32 UTC, alexec reviewed
Needs @jessesuen approval for proto changes.

2021-01-25 15:32 UTC, alexec commented on pkg/apiclient/info/info.proto
> +    string serviceAccount = 6;
I think it should probably be consistent with PodSpec which would be serviceAccountName:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

2021-01-25 19:39 UTC, jessesuen approved these changes
Agree with @alexec. Conditional approval provided we rename to serviceAccountName.

2021-01-26 00:47 UTC, alexec approved these changes

2021-01-26 00:47 UTC, alexec commented
I think e2e test failure is unrelated. Re-running.

2021-01-27 20:33 UTC, alexec commented
Please sync with master to fix conflicts introduced by v2.

2021-01-27 20:33 UTC, alexec requested changes
Needs rebase/merge from master.

2021-01-27 22:23 UTC, tczhao commented
> Needs rebase/merge from master.

Done

2021-01-27 23:18 UTC, alexec approved these changes

2021-01-27 23:34 UTC, merged

2021-01-27 23:34 UTC, alexec commented
@simster7 we might want to back-part this one.