fix: Coalesce UI filtering menus
argoproj/argo pull request #4972
Opened 2021-01-29 18:35 UTC by simster7

**WIP**. Menus are now coalesced but no good unified UX yet, testing different options

Signed-off-by: Simon Behar <simbeh7@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

2021-01-29 19:10 UTC, alexec commented
Could I suggest something a bit bigger than the drop-down - you have to scroll the drop-down which discourages usage.

What about a bespoke floating panel, like this:

![image](https://user-images.githubusercontent.com/1142830/106317026-87b30a80-6222-11eb-983e-77d9ab5e32b1.png)

2021-01-29 19:10 UTC, alexec commented
Tippy might work for this.

2021-01-29 19:16 UTC, simster7 commented
Yep, was chatting with Remington about some ideas and we considered this as well

2021-02-01 16:56 UTC, simster7 commented
Current view

<img width="464" alt="image" src="https://user-images.githubusercontent.com/614838/106490988-3f3a5d80-646b-11eb-9697-6fbc98ab6829.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/614838/106491058-524d2d80-646b-11eb-8d90-cd580f6c6e22.png">

2021-02-01 18:21 UTC, alexec reviewed
it seems to me that this combine two things

* drop-down
* floating panel

Can you separate them  please?

2021-02-02 19:40 UTC, alexec requested changes
See comment.

2021-02-02 21:35 UTC, simster7 commented
> it seems to me that this combine two things
>
>   drop-down
>    floating panel
>
> Can you separate them please?

Sorry, don't think I know what you mean. Could you clarify please?

2021-02-02 21:45 UTC, simster7 commented
@alexec

2021-02-02 21:52 UTC, alexec commented
> Sorry, don't think I know what you mean. Could you clarify please?

Single responsibility principle. Rather than write a component that can must do both jobs - pop-over + drop-down - write one component for the pop-over and another for the drop-down.

2021-02-02 21:54 UTC, simster7 commented
> Single responsibility principle. Rather than write a component that must do both jobs - pop-over + drop-down - write one component for the pop-over and another for the drop-down.

Understood, thanks!

2021-02-02 22:10 UTC, simster7 reviewed
Hey @alexec, I took another look at the code after reading your message on Slack and I do see that the "filtering" and the "dropdown" aspects of the code are separated (see comments). Let me know what you think and if you think I'm still misunderstanding the change you want.

2021-02-02 22:10 UTC, simster7 commented on ui/src/app/shared/components/dropdown/dropdown.tsx
> +                        {children}
This is where we display the "filter" part of the code. This function does not make any assumptions about the content of `children` (which comes from `props.children`): The code in this function is only concerned with displaying the drop down menu and has no code regarding the actual list to be filtered.

2021-02-02 22:10 UTC, simster7 commented on ui/src/app/shared/components/filter-drop-down.tsx
> +            </ul>
This is where we display the "filtering" aspect. It is passed as an argument (through `props.children`) to `DropDown`. None of the code here (even the code that deals with `onChange` is known/used/needed by `DropDown`, it is simply passed through and displayed.

2021-02-02 22:10 UTC, simster7 commented on ui/src/app/shared/components/filter-drop-down.tsx
> +export const FilterDropDown = (props: FilterDropDownProps) => {
This component is called `FilterDropDown`, but since it uses the abstract `DropDown` and adds filtering to it as content, I think it's a fair name.

2021-02-02 22:25 UTC, alexec approved these changes

2021-02-02 22:53 UTC, merged